name: MLOps CI Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install core dependencies
        run: |
          pip install -r requirements.txt

      - name: Run CML
        uses: iterative/setup-cml@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Pull artifacts from DVC
        run: dvc pull

      - name: Run Pytest and Save Report
        run: pytest --maxfail=1 --disable-warnings -q > report.txt

      - name: Create CML report on Pull Request
        if: github.event_name == 'pull_request'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## ✅ MLOps CI Report" > cml_report.md
          echo "**Branch:** ${{ github.head_ref }}" >> cml_report.md
          echo "**Commit:** \`${{ github.sha }}\`" >> cml_report.md
          echo "" >> cml_report.md
          echo "### 🧪 Test Summary" >> cml_report.md
          cat report.txt >> cml_report.md
          echo "" >> cml_report.md
          echo "---" >> cml_report.md
          echo "_Generated automatically by CML_" >> cml_report.md
          cml comment create cml_report.md
